import type { ServiceReport } from "./schemas";

const baseEvents = (reference: string, status: ServiceReport["status"], createdAt: string) => [
  { id: `${reference}-e1`, status: "reported" as const, at: createdAt, note: "Report received by FixSA Voice demo.", public: true, actor: "agent" as const },
  ...(status !== "reported"
    ? [{ id: `${reference}-e2`, status: "triaged" as const, at: "2026-09-18T08:35:00+02:00", note: "Synthetic operator reviewed category and priority.", public: true, actor: "operator" as const }]
    : []),
  ...(["assigned", "in_progress", "resolved", "closed"].includes(status)
    ? [{ id: `${reference}-e3`, status: "assigned" as const, at: "2026-09-18T09:10:00+02:00", note: "Assigned to a demo field team.", public: true, actor: "operator" as const }]
    : []),
  ...(["in_progress", "resolved", "closed"].includes(status)
    ? [{ id: `${reference}-e4`, status: "in_progress" as const, at: "2026-09-18T10:20:00+02:00", note: "Demo team marked work as started.", public: true, actor: "operator" as const }]
    : []),
];

export const seedReports: ServiceReport[] = [
  {
    id: "rpt-water-001",
    reference: "FSA-2026-1842",
    createdAt: "2026-09-18T07:42:00+02:00",
    updatedAt: "2026-09-18T10:20:00+02:00",
    source: "voice",
    status: "in_progress",
    priority: "urgent",
    fields: {
      category: "water_leak",
      location: { address: "Tamboti Road, near Ivory Park Clinic", area: "Ivory Park", landmark: "Ivory Park Clinic", latitude: -25.9979, longitude: 28.1907, precision: "confirmed" },
      duration: "Since yesterday afternoon",
      severity: "high",
      hazards: ["Road flooding", "Slippery surface"],
      peopleAffected: 80,
      details: "Large clean-water leak crossing the road and flooding the lane nearest the clinic.",
    },
    transcript: [
      { id: "t1", speaker: "resident", text: "There is a large water leak near the clinic on Tamboti Road. It started yesterday and the road is flooding.", timestamp: "2026-09-18T07:41:12+02:00", final: true },
      { id: "t2", speaker: "agent", text: "I heard a large water leak near Ivory Park Clinic on Tamboti Road, active since yesterday and flooding the road. Is that correct?", timestamp: "2026-09-18T07:41:24+02:00", final: true },
      { id: "t3", speaker: "resident", text: "Yes, that is correct.", timestamp: "2026-09-18T07:41:31+02:00", final: true },
    ],
    evidence: [{ id: "ev1", type: "transcript", name: "Confirmed voice transcript", addedAt: "2026-09-18T07:42:00+02:00", public: false }],
    statusEvents: baseEvents("FSA-2026-1842", "in_progress", "2026-09-18T07:42:00+02:00"),
    publicNotes: ["A demo field team is assessing the affected lane."],
    internalNotes: ["Synthetic report for hackathon demonstration only."],
    assignee: "Water response · Team 2",
    slaHours: 4,
    slaDueAt: "2026-09-18T11:42:00+02:00",
    duplicateOf: null,
    mergedReportIds: ["rpt-water-duplicate"],
    audioRetention: "ephemeral_deleted",
    safetyHold: false,
    synthetic: true,
  },
  {
    id: "rpt-pothole-002",
    reference: "FSA-2026-1837",
    createdAt: "2026-09-17T15:16:00+02:00",
    updatedAt: "2026-09-18T08:35:00+02:00",
    source: "text",
    status: "triaged",
    priority: "priority",
    fields: {
      category: "pothole",
      location: { address: "Republic Road at Market Street", area: "Randburg", landmark: "Taxi rank entrance", latitude: -26.0991, longitude: 28.0067, precision: "confirmed" },
      duration: "Approximately one week",
      severity: "high",
      hazards: ["Vehicles swerving", "Cyclist risk"],
      peopleAffected: 120,
      details: "Deep pothole in the left lane near the taxi rank entrance; vehicles are swerving into oncoming traffic.",
    },
    transcript: [{ id: "p1", speaker: "resident", text: "A deep pothole at Republic Road and Market Street is making cars swerve.", timestamp: "2026-09-17T15:15:00+02:00", final: true }],
    evidence: [{ id: "pev1", type: "photo", name: "road-surface-demo.jpg", addedAt: "2026-09-17T15:16:00+02:00", public: true }],
    statusEvents: baseEvents("FSA-2026-1837", "triaged", "2026-09-17T15:16:00+02:00"),
    publicNotes: ["Report has been reviewed in the synthetic triage queue."],
    internalNotes: ["Consider lane-risk signage in a real integration."],
    assignee: null,
    slaHours: 24,
    slaDueAt: "2026-09-18T15:16:00+02:00",
    duplicateOf: null,
    mergedReportIds: [],
    audioRetention: "not_recorded",
    safetyHold: false,
    synthetic: true,
  },
  {
    id: "rpt-light-003",
    reference: "FSA-2026-1811",
    createdAt: "2026-09-15T19:04:00+02:00",
    updatedAt: "2026-09-18T07:10:00+02:00",
    source: "voice",
    status: "resolved",
    priority: "routine",
    fields: {
      category: "broken_streetlight",
      location: { address: "Makhado Avenue", area: "Tembisa", landmark: "Community hall", latitude: -25.9984, longitude: 28.2252, precision: "approximate" },
      duration: "Three nights",
      severity: "moderate",
      hazards: ["Poor visibility"],
      peopleAffected: 35,
      details: "Two streetlights outside the community hall were not switching on after dark.",
    },
    transcript: [{ id: "l1", speaker: "resident", text: "Two lights outside the community hall have been off for three nights.", timestamp: "2026-09-15T19:03:00+02:00", final: true }],
    evidence: [],
    statusEvents: [
      ...baseEvents("FSA-2026-1811", "in_progress", "2026-09-15T19:04:00+02:00"),
      { id: "FSA-2026-1811-e5", status: "resolved", at: "2026-09-18T07:10:00+02:00", note: "Synthetic resolution: photocell replaced.", public: true, actor: "operator" },
    ],
    publicNotes: ["Demo repair completed; awaiting resident confirmation."],
    internalNotes: ["Synthetic asset identifier: LT-DEMO-044."],
    assignee: "Lighting · Crew 1",
    slaHours: 72,
    slaDueAt: "2026-09-18T19:04:00+02:00",
    duplicateOf: null,
    mergedReportIds: [],
    audioRetention: "ephemeral_deleted",
    safetyHold: false,
    resolutionVerification: { state: "pending", outcome: null, statement: "", verifiedAt: null, method: "judge_demo" },
    synthetic: true,
  },
  {
    id: "rpt-sewer-004",
    reference: "FSA-2026-1803",
    createdAt: "2026-09-14T09:22:00+02:00",
    updatedAt: "2026-09-18T06:00:00+02:00",
    source: "voice",
    status: "assigned",
    priority: "urgent",
    fields: {
      category: "sewer_overflow",
      location: { address: "Madalane Street", area: "Alexandra", landmark: "Primary school gate", latitude: -26.1054, longitude: 28.0996, precision: "confirmed" },
      duration: "Four days",
      severity: "critical",
      hazards: ["Public health risk", "Children nearby"],
      peopleAffected: 210,
      details: "Wastewater overflowing from a manhole near the primary school gate and running into the pedestrian path.",
    },
    transcript: [{ id: "s1", speaker: "resident", text: "The sewer near the school gate is overflowing onto the walkway.", timestamp: "2026-09-14T09:21:00+02:00", final: true }],
    evidence: [],
    statusEvents: baseEvents("FSA-2026-1803", "assigned", "2026-09-14T09:22:00+02:00"),
    publicNotes: ["Demo sanitation team assigned."],
    internalNotes: ["Synthetic public-health escalation."],
    assignee: "Sanitation · Team 4",
    slaHours: 4,
    slaDueAt: "2026-09-14T13:22:00+02:00",
    duplicateOf: null,
    mergedReportIds: [],
    audioRetention: "ephemeral_deleted",
    safetyHold: false,
    synthetic: true,
  },
];

export const defaultReport = seedReports[0];
