import Link from "next/link";
import { AlertTriangle, ArrowRight, BadgeCheck, Bolt, Construction, Droplets, GitMerge, Mic2, ScanSearch, Wrench } from "lucide-react";
import { PageHeader } from "@/components/Ui";

const scenarios = [
  { id:"proof", icon:BadgeCheck, title:"Proof of Fix", text:"A resident checks whether a claimed repair actually worked.", steps:["Resolved ticket becomes pending verification", "Resident confirms, partially confirms, or disputes", "Failed work reopens automatically", "Public and operator audit trails update"], cta:"Verify a repair", href:"/verify?ref=FSA-2026-1811" },
  { id:"water", icon:Droplets, title:"Large water leak", text:"A resident reports road flooding near a clinic.", steps:["Live transcript streams word-by-word", "Fields extracted and severity assigned", "Nearby report search runs", "Read-back and confirmation gate"], cta:"Run water leak" },
  { id:"electricity", icon:Bolt, title:"Dangerous electricity fault", text:"Exposed cable is sparking beside a school.", steps:["Immediate-danger language detected", "Ordinary tool flow is stopped", "No emergency number is fabricated", "Official emergency guidance shown"], cta:"Test safety stop" },
  { id:"pothole", icon:Construction, title:"Hazardous pothole", text:"Cars are swerving around a deep road defect.", steps:["Road category classified", "Traffic hazard changes priority", "Landmark clarifies location", "Synthetic work order created"], cta:"Run pothole" },
  { id:"duplicate", icon:GitMerge, title:"Duplicate report", text:"A second resident describes the same leak.", steps:["Location and category candidates found", "Semantic overlap scored", "Match rationale explained", "Evidence merged only after consent"], cta:"Test duplicate merge" },
];

export default function DemoScenariosPage() { return <div className="page-container"><PageHeader eyebrow="Judge mode" title="Five journeys. Every behaviour visible." description="One-click scenarios use deterministic synthetic transcripts and the same tool contracts as real AssemblyAI mode."/><div className="callout" style={{ marginBottom:26 }}><Mic2/><div><strong>What AssemblyAI does in real mode</strong><p>The Voice Agent API streams the resident transcript, manages turn-taking and spoken replies, and issues JSON-schema tool calls. FixSA validates and executes the civic workflow tools, then returns structured results.</p></div></div><div className="two-grid">{scenarios.map(({ id, icon:Icon, title, text, steps, cta, href }) => <article className={`scenario-card ${id === "proof" ? "scenario-featured" : ""}`} key={id}><div className="scenario-icon"><Icon/></div><h2>{title}</h2><p>{text}</p><ol className="assembly-steps">{steps.map((step) => <li key={step}>{step}</li>)}</ol><Link className="button button-primary" href={href || `/report?scenario=${id}`}>{cta} <ArrowRight size={17}/></Link></article>)}</div><section className="panel" style={{ marginTop:28 }}><div className="panel-header"><div><p className="eyebrow">Tool-call evidence</p><h2>Shared contracts, two adapters</h2></div><Wrench/></div><div className="three-grid"><div><ScanSearch/><h3>Understand</h3><p><code>classify_service_issue</code> and <code>search_nearby_reports</code> turn free speech into explainable structure.</p></div><div><AlertTriangle/><h3>Guard</h3><p><code>confirm_report_details</code> plus the application safety classifier prevents unconfirmed or dangerous ordinary submission.</p></div><div><GitMerge/><h3>Act and verify</h3><p><code>create_service_request</code>, duplicate tools, and <code>verify_resolution</code> operate only on validated synthetic data.</p></div></div></section></div>; }
