import Link from "next/link";
import { ArrowRight, ClockAlert, GitMerge, Radio, TimerReset } from "lucide-react";
import { MapPanel } from "@/components/MapPanel";
import { PageHeader, PriorityBadge, StatCard, StatusBadge } from "@/components/Ui";
import { seedReports } from "@/lib/seed";
import { categoryLabels } from "@/lib/schemas";

export default function OperationsDashboard() {
  return <><PageHeader eyebrow="Operator overview · synthetic metrics" title="Service pressure, at a glance." description="A judge-ready operational view of intake, duplicates, SLA exposure, and current activity." actions={<Link className="button button-primary" href="/ops/reports">Open queue <ArrowRight size={17}/></Link>}/>
    <div className="kpi-grid"><StatCard label="Open reports" value="38" trend="↑ 8 in the last 24 hours"/><StatCard label="SLA at risk" value="6" trend="2 already breached" tone="warning"/><StatCard label="Duplicate reduction" value="21%" trend="Synthetic 30-day estimate" tone="positive"/><StatCard label="Average report time" value="01:42" trend="34 sec faster than typed demo" tone="positive"/></div>
    <div className="dashboard-grid"><section className="panel"><div className="panel-header"><div><p className="eyebrow">Incoming queue</p><h2>Needs operator attention</h2></div><Radio/></div><div className="table-wrap"><table><thead><tr><th>Reference</th><th>Issue</th><th>Area</th><th>Priority</th><th>Status</th></tr></thead><tbody>{seedReports.map((report) => <tr key={report.id}><td><Link href={`/ops/report?id=${report.id}`}>{report.reference}</Link></td><td>{categoryLabels[report.fields.category]}</td><td>{report.fields.location.area}</td><td><PriorityBadge priority={report.priority}/></td><td><StatusBadge status={report.status}/></td></tr>)}</tbody></table></div></section><section className="panel"><div className="panel-header"><div><p className="eyebrow">SLA watch</p><h2>Pressure signals</h2></div><ClockAlert/></div><div className="metric-bars"><Metric label="Critical / urgent" value="6" width="78%"/><Metric label="Due within 4 hours" value="11" width="61%"/><Metric label="Unassigned" value="9" width="48%"/><Metric label="Possible duplicates" value="4" width="29%"/></div><Link href="/ops/analytics" className="button button-ghost button-wide" style={{ marginTop: 28 }}><TimerReset size={17}/> Review SLA trends</Link></section></div>
    <section className="panel" style={{ marginTop: 20 }}><div className="panel-header"><div><p className="eyebrow">Geographic triage</p><h2>Open issue distribution</h2></div><Link href="/ops/map">Open full map →</Link></div><MapPanel reports={seedReports.filter((report) => !["resolved","closed"].includes(report.status))}/></section>
    <div className="two-grid" style={{ marginTop: 20 }}><section className="panel"><div className="panel-header"><div><p className="eyebrow">Severity mix</p><h2>Intake by impact</h2></div></div><div className="metric-bars"><Metric label="Critical" value="8%" width="8%"/><Metric label="High" value="37%" width="37%"/><Metric label="Moderate" value="42%" width="42%"/><Metric label="Low" value="13%" width="13%"/></div></section><section className="panel"><div className="panel-header"><div><p className="eyebrow">Recent activity</p><h2>Immutable demo events</h2></div><GitMerge/></div><ul className="audit-list"><li><strong>10:20</strong> · FSA-2026-1842 moved to In progress</li><li><strong>09:10</strong> · Water Team 2 accepted assignment</li><li><strong>08:35</strong> · FSA-2026-1837 triaged as Priority</li><li><strong>08:14</strong> · Duplicate evidence merged into FSA-2026-1842</li></ul></section></div>
  </>;
}

function Metric({ label, value, width }: { label: string; value: string; width: string }) { return <div className="metric-bar"><label><span>{label}</span><strong>{value}</strong></label><div className="bar-track"><span style={{ "--width": width } as React.CSSProperties}/></div></div>; }
