"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { ArrowLeft, BadgeCheck, FileAudio, GitMerge, History, Image as ImageIcon, LockKeyhole, MapPin, MessageSquareText, RotateCcw, UserRound } from "lucide-react";
import { loadReports, upsertReport } from "@/lib/demo-store";
import { categoryLabels, reportStatuses, statusLabels, type ReportStatus, type ServiceReport } from "@/lib/schemas";
import { MapPanel } from "./MapPanel";
import { EmptyState, PageHeader, PriorityBadge, StatusBadge } from "./Ui";

export function ReportDetailClient({ id }: { id: string }) {
  const [report, setReport] = useState<ServiceReport | null>(null);
  const [saved, setSaved] = useState("");
  useEffect(() => {
    const frame = window.requestAnimationFrame(() => setReport(loadReports().find((item) => item.id === id) || null));
    return () => window.cancelAnimationFrame(frame);
  }, [id]);
  if (!report) return <EmptyState title="Report not found" description="This synthetic record may have been reset." action={<Link className="button button-ghost" href="/ops/reports"><ArrowLeft size={17}/> Back to reports</Link>}/>;
  const update = (changes: Partial<ServiceReport>, audit: string) => {
    const now = new Date().toISOString();
    const updated = { ...report, ...changes, updatedAt: now, statusEvents: [...report.statusEvents, { id: crypto.randomUUID(), status: changes.status || report.status, at: now, note: audit, public: false, actor: "operator" as const }] };
    upsertReport(updated); setReport(updated); setSaved("Saved to this browser with an immutable audit event.");
  };
  return <><PageHeader eyebrow={`${report.reference} · Synthetic record`} title={categoryLabels[report.fields.category]} description={`${report.fields.location.address}, ${report.fields.location.area}`} actions={<Link className="button button-ghost" href="/ops/reports"><ArrowLeft size={17}/> Queue</Link>}/>
    <div className="kpi-grid"><div className="stat-card"><p>Status</p><StatusBadge status={report.status}/><span>Last update {new Date(report.updatedAt).toLocaleString("en-ZA", { dateStyle:"medium", timeStyle:"short" })}</span></div><div className="stat-card"><p>Priority & SLA</p><PriorityBadge priority={report.priority}/><span>{report.slaHours}h target · due {new Date(report.slaDueAt).toLocaleString("en-ZA", { dateStyle:"medium", timeStyle:"short" })}</span></div><div className="stat-card"><p>Assignment</p><strong style={{ fontSize:"1rem" }}>{report.assignee || "Unassigned"}</strong><span>Demo operator controlled</span></div><div className="stat-card"><p>Audio retention</p><strong style={{ fontSize:"1rem" }}>{report.audioRetention.replaceAll("_"," ")}</strong><span>Visible retention state</span></div></div>
    {report.resolutionVerification && <section className={`proof-public ${report.resolutionVerification.state}`} style={{ marginBottom: 22 }}>{report.resolutionVerification.state === "verified" ? <BadgeCheck/> : <RotateCcw/>}<div><p className="eyebrow">Proof of Fix</p><strong>{report.resolutionVerification.state === "pending" ? "Awaiting resident verification" : report.resolutionVerification.state === "verified" ? "Resident independently confirmed this repair" : "Resident challenged this closure"}</strong><p>{report.resolutionVerification.state === "pending" ? "Resolved by the synthetic crew, but not yet counted as resident-confirmed." : report.resolutionVerification.statement}</p>{report.resolutionVerification.state === "pending" && <Link className="button button-primary button-small" href={`/verify?ref=${report.reference}`}>Run resident check</Link>}</div></section>}
    <div className="dashboard-grid"><div className="settings-list">
      <section className="panel"><div className="panel-header"><div><p className="eyebrow">Structured report</p><h2>Incident details</h2></div><MessageSquareText/></div><dl className="detail-grid"><div><dt>Duration</dt><dd>{report.fields.duration}</dd></div><div><dt>Severity</dt><dd>{report.fields.severity}</dd></div><div><dt>People affected</dt><dd>{report.fields.peopleAffected}</dd></div><div><dt>Landmark</dt><dd>{report.fields.location.landmark}</dd></div><div><dt>Precision</dt><dd>{report.fields.location.precision}</dd></div><div><dt>Source</dt><dd>{report.source.replace("_"," ")}</dd></div></dl><h3 style={{ marginTop:24 }}>Details</h3><p>{report.fields.details}</p><h3>Hazards</h3><div className="extraction-row">{report.fields.hazards.map((hazard) => <span className="chip" key={hazard}>{hazard}</span>)}</div></section>
      <section className="panel"><div className="panel-header"><div><p className="eyebrow">Conversation</p><h2>Transcript timeline</h2></div><FileAudio/></div><ul className="audit-list">{report.transcript.map((item) => <li key={item.id}><strong>{item.speaker === "resident" ? "Resident" : "FixSA Voice"}</strong><p>{item.text}</p><time>{new Date(item.timestamp).toLocaleTimeString("en-ZA", { hour:"2-digit", minute:"2-digit" })} · final transcript</time></li>)}</ul><div className="public-policy"><LockKeyhole size={16}/> Audio: {report.audioRetention.replaceAll("_", " ")}. This demo stores text only.</div></section>
      <section className="panel"><div className="panel-header"><div><p className="eyebrow">Evidence</p><h2>{report.evidence.length} attached items</h2></div><ImageIcon/></div>{report.evidence.length ? <ul className="audit-list">{report.evidence.map((item) => <li key={item.id}><strong>{item.name}</strong><p>{item.type} · {item.public ? "resident-visible" : "operator-only"}</p></li>)}</ul> : <p>No evidence attached.</p>}</section>
      <section className="panel"><div className="panel-header"><div><p className="eyebrow">Immutable events</p><h2>Audit trail</h2></div><History/></div><ul className="audit-list">{[...report.statusEvents].reverse().map((event) => <li key={event.id}><strong>{statusLabels[event.status]} · {event.actor}</strong><p>{event.note}</p><time>{new Date(event.at).toLocaleString("en-ZA", { dateStyle:"medium", timeStyle:"short" })}</time></li>)}</ul></section>
    </div><aside className="settings-list"><section className="panel"><p className="eyebrow">Safe demo controls</p><div className="field"><label htmlFor="detail-status">Status</label><select id="detail-status" value={report.status} onChange={(event) => update({ status: event.target.value as ReportStatus }, `Demo status changed from ${report.status} to ${event.target.value}.`)}>{reportStatuses.map((status) => <option key={status} value={status}>{statusLabels[status]}</option>)}</select></div><div className="field" style={{ marginTop:14 }}><label htmlFor="assignee">Assignee</label><select id="assignee" value={report.assignee || ""} onChange={(event) => update({ assignee: event.target.value || null }, `Demo assignee changed to ${event.target.value || "unassigned"}.`)}><option value="">Unassigned</option><option>Water response · Team 2</option><option>Roads · Crew 3</option><option>Lighting · Crew 1</option><option>Sanitation · Team 4</option></select></div>{saved && <p role="status" style={{ marginTop:12 }}>{saved}</p>}</section><section className="panel"><div className="panel-header"><div><p className="eyebrow">Location</p><h2>Map</h2></div><MapPin/></div><MapPanel reports={[report]}/></section><section className="panel"><div className="panel-header"><div><p className="eyebrow">Relationships</p><h2>Duplicate history</h2></div><GitMerge/></div>{report.mergedReportIds.length ? <p>{report.mergedReportIds.length} corroborating demo report{report.mergedReportIds.length === 1 ? "" : "s"} merged. Merge is reversible in the duplicate review screen.</p> : <p>No merged reports. Duplicate of: {report.duplicateOf || "none"}.</p>}<Link className="button button-ghost button-wide" href="/ops/duplicates">Review duplicates</Link></section><section className="panel"><div className="panel-header"><div><p className="eyebrow">Notes</p><h2>Visibility split</h2></div><UserRound/></div><h3>Resident-visible</h3>{report.publicNotes.map((note) => <p key={note}>{note}</p>)}<h3>Internal only</h3>{report.internalNotes.map((note) => <p key={note}>{note}</p>)}</section></aside></div>
  </>;
}

export function ReportDetailEntry() {
  const search = useSearchParams();
  return <ReportDetailClient id={search.get("id") || ""}/>;
}
